# Generated by Django 3.2.6 on 2021-12-17 16:21

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('altitude_accuracy', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('nurse_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.nursead')),
            ],
        ),
        migrations.CreateModel(
            name='RouteLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('color', models.CharField(default='#f5365c', help_text='Use hexadecimal format like #f5365c', max_length=7, validators=[django.core.validators.RegexValidator('#[a-fA-F0-9]{6}')])),
                ('nurse_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.nursead')),
            ],
        ),
    ]
