# Generated by Django 3.2.6 on 2021-11-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeline',
            name='ad_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackedpoint',
            name='ad_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
