# Generated by Django 3.2.6 on 2021-11-18 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20211118_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeline',
            name='color',
            field=models.CharField(default='#f5365c', help_text='Use hexadecimal format like #f5365c', max_length=7, validators=[django.core.validators.RegexValidator('#[a-fA-F0-9]{6}')]),
        ),
    ]
