# Generated by Django 3.2.6 on 2021-11-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=1000)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('service_type', models.CharField(choices=[('1', 'Elderly care'), ('2', 'Caring for people with disabilities'), ('3', 'Outpatient services')], max_length=20)),
                ('sex', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man')], max_length=10)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NurseAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.CharField(max_length=10000)),
                ('ad_id', models.CharField(max_length=10000)),
                ('situation', models.CharField(choices=[('accepted', 'Accepted'), ('started', 'Started'), ('finished', 'Finished')], default='accepted', max_length=10)),
            ],
        ),
    ]
