# Generated by Django 3.2.6 on 2021-11-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='nursead',
            name='situation',
        ),
    ]
