# Generated by Django 3.2.6 on 2021-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.CharField(max_length=10000)),
                ('ad_id', models.CharField(max_length=10000)),
                ('current', models.BooleanField(default=True)),
            ],
        ),
    ]
