# Generated by Django 3.2.6 on 2021-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211116_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursead',
            name='situation',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('started', 'Started'), ('finished', 'Finished')], default='accepted', max_length=10),
        ),
    ]
