# Generated by Django 3.2.6 on 2021-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nursead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursead',
            name='current',
            field=models.BooleanField(),
        ),
    ]
