# Generated by Django 3.2.6 on 2021-11-23 11:47

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[apps.users.validators.validate_file_size]),
        ),
    ]
