# Generated by Django 3.2.6 on 2021-12-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=2)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=1000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('1', 'Elderly care'), ('2', 'Caring for people with disabilities'), ('3', 'Outpatient services')], max_length=2)),
                ('urgency', models.CharField(choices=[('1', 'Urgent'), ('0', 'Non-urgent')], default='0', max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NurseAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('S', 'Started'), ('F', 'Finished')], default='A', max_length=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
            ],
        ),
    ]
