# Generated by Django 3.2.6 on 2021-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='gender',
            field=models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='service_type',
            field=models.CharField(choices=[('0', 'Elderly care'), ('1', 'Caring for people with disabilities'), ('2', 'Outpatient services')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nursead',
            name='situation',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Started'), ('F', 'Finished')], default='A', max_length=10),
        ),
    ]
