# Generated by Django 3.2.6 on 2021-12-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='service_type',
            field=models.CharField(choices=[('1', 'Elderly care'), ('2', 'Caring for people with disabilities'), ('3', 'Outpatient services'), ('4', 'Injection services'), ('5', 'Blood test'), ('6', 'PCR test')], max_length=2),
        ),
    ]
