# Generated by Django 3.2.6 on 2021-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20211207_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
