# Generated by Django 3.2.6 on 2021-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20211207_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='gender',
            field=models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ad',
            name='service_type',
            field=models.CharField(choices=[('1', 'Elderly care'), ('2', 'Caring for people with disabilities'), ('3', 'Outpatient services')], max_length=2),
        ),
        migrations.AlterField(
            model_name='nursead',
            name='situation',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Started'), ('F', 'Finished')], default='A', max_length=2),
        ),
    ]
