# Generated by Django 3.2.6 on 2021-12-29 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('review', models.TextField(null=True)),
                ('nurse_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ads.nursead')),
            ],
        ),
    ]
