# Generated by Django 3.2.6 on 2021-12-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20211212_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_urgent',
            field=models.CharField(choices=[('1', 'Urgent'), ('0', 'Non-urgent')], default='0', max_length=2),
        ),
    ]
