# Generated by Django 3.2.6 on 2022-02-23 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 23, 17, 17, 26, 236435, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
