# Generated by Django 3.2.6 on 2021-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_nurse_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
